/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package io.github.joaomarccos.gui.client.rmi;

import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author joaomarcos
 */
public final class MainFrame extends javax.swing.JFrame {

    private final Chat chat;
    private User user;

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        this.setResizable(false);
        this.setContentPane(new LoginPanel(this));
        this.setLocationRelativeTo(null);
        this.setVisible(true);
        this.chat = new Chat();
        verifyConnect(this);
    }

    public Chat getChat() {
        return chat;
    }

    public User getUser() {
        return user;
    }

    public void setUser(User user) {
        this.user = user;
    }
    
    public void logout(){
        this.setContentPane(new LoginPanel());
        this.setVisible(true);
    }
    
    public void verifyConnect(final MainFrame mainFrame) {
        Runnable r;
        r = new Runnable() {
            
            private boolean disconnected = false;
            
            @Override
            public void run() {
                while (true) {
                    try {
                        Thread.sleep(5000);
                        System.out.println("Verificando concexão...");
                        mainFrame.getChat().ping();
                        if(disconnected){
                            mainFrame.getChat().tryConnect();
                            disconnected = false;
                        }
                    } catch (NotConnectedToServerException | InterruptedException ex) {
                        disconnected = true;
                        mainFrame.setContentPane(new LoginPanel(mainFrame));
                        mainFrame.setVisible(true);
                        Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
                    } 
                }
            }
        };

        new Thread(r).start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JLabelLoading = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Chat RMI");

        JLabelLoading.setText("Carregando...");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(168, 168, 168)
                .addComponent(JLabelLoading)
                .addContainerGap(158, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(JLabelLoading)
                .addContainerGap(241, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                MainFrame mainFrame = new MainFrame();
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JLabelLoading;
    // End of variables declaration//GEN-END:variables
}
